#!/bin/bash
#
#	template based on:  https://github.com/scitran-apps/fsl-bet/blob/master/run
#
#   DeepMedic needs at least 6 GB memory limit (fails at 4GB)
#

CONTAINER="[captk-histogram-matching]"
echo -e "$CONTAINER  Initiated"

###############################################################################
## Built to flywheel-v0 spec.
FLYWHEEL_BASE=/flywheel/v0
OUTPUT_DIR=$FLYWHEEL_BASE/output
input_im_DIR=$FLYWHEEL_BASE/input/input_image
ref_im_DIR=$FLYWHEEL_BASE/input/reference_image
MANIFEST=$FLYWHEEL_BASE/manifest.json
CONFIG_FILE=$FLYWHEEL_BASE/config.json

###############################################################################
## Configure the ENV
export USER=Flywheel

###############################################################################
## Execute the main processes
function jsonValue() {
KEY=$1
num=$2
awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}

## get all user configurations
if [[ -f $CONFIG_FILE ]]; then
  echo "$CONTAINER  $CONFIG_FILE found. Loading config..."

  histogram_bins="$(cat $CONFIG_FILE | jsonValue histogram_bins)"
  histogram_quantiles="$(cat $CONFIG_FILE | jsonValue histogram_quantiles)"
  output_fn="$(cat $CONFIG_FILE | jsonValue output_file_name)"

else
  echo "$CONTAINER  $CONFIG_FILE not found. Loading defaults from $MANIFEST..."

  histogram_bins="$(cat $MANIFEST | jsonValue histogram_bins default)"
  histogram_quantiles="$(cat $MANIFEST | jsonValue histogram_quantiles default)"
  output_fn="$(cat $MANIFEST | jsonValue output_file_name default)"

fi

## convert string to int
# histogram_bins=$((histogram_bins))
# histogram_quantiles=$((histogram_quantiles))
# echo "${histogram_quantiles}"
# echo "$(($histogram_quantiles))"

## Find the input files
input_im_file=$(find $input_im_DIR/* -maxdepth 0 -type f -name "*.nii*")
ref_im_file=$(find $ref_im_DIR/* -maxdepth 0 -type f -name "*.nii*")

## define output
out_path="output/"
out_path+=$output_fn
out_path="$(echo -e "${out_path}" | tr -d '[:space:]')"

## If necessary input files are found, run the thing
if [[ -f $input_im_file ]] && \
   [[ -f $ref_im_file ]] ; then

  CaPTk_dir=/opt/captk/1.8.1/usr # path to install (in Docker container)

  echo "$CONTAINER  Running CaPTk Histogram Matching"
  ${CaPTk_dir}/bin/Preprocessing \
    -i "${input_im_file}" \
    -o "${out_path}" \
    -hi "${ref_im_file}" \
    -hb "${histogram_bins}" -hq "${histogram_quantiles}"

################# Finish up #################
  STATUS=$?
else
  echo "$CONTAINER  Input files not found!"
  exit 1
fi

# Check exit status
if [[ $STATUS == 0 ]]
  then
    echo -e "$CONTAINER  Done!"

  else
    echo "$CONTAINER  command returned a non-zero exit code = [$STATUS]."
    exit 1
fi

exit 0
